import { ComplianceDate, ComplianceWindow } from "@/components/compliance-date";
import { StatusBadge } from "@/components/status-badge";
import { Why } from "@/components/why";
import {
  getUrgency,
  missedObligationConsequence,
} from "@/lib/compliance-intelligence";
import {
  plainEnumLabel,
  requirementLabel,
  requiredActionLabel,
} from "@/lib/labels";

export function ObligationIntelligenceCard({
  obligation,
  today,
}: {
  obligation: {
    id: string;
    type: string;
    category?: "SAMPLE" | "INSPECTION" | "MAINTENANCE" | "REPORTING_ACTION";
    earliest: string | Date | null;
    targetStart: string | Date | null;
    targetEnd: string | Date | null;
    latest: string | Date | null;
    priority: string;
    status: string;
    reason: string;
    sourceCitation?: string | null;
    ruleSetVersion?: string | null;
    trigger?: { id: string; type: string; date: string | Date } | null;
  };
  today: string;
}) {
  const latest = obligation.latest
    ? typeof obligation.latest === "string"
      ? obligation.latest
      : obligation.latest.toISOString().slice(0, 10)
    : null;
  const targetStart = obligation.targetStart
    ? typeof obligation.targetStart === "string"
      ? obligation.targetStart
      : obligation.targetStart.toISOString().slice(0, 10)
    : null;
  const urgency = getUrgency({
    today,
    status: obligation.status,
    priority: obligation.priority,
    latestDueDate: latest,
    targetStartDate: targetStart,
  });
  return (
    <article className="border-b border-slate-200 py-4 last:border-b-0">
      <div className="grid gap-4 lg:grid-cols-[minmax(260px,1.2fr)_minmax(210px,.8fr)_auto] lg:items-center">
        <div className="min-w-0">
          {obligation.category && (
            <div className="label">
              {obligation.category === "REPORTING_ACTION"
                ? "Reporting or corrective action"
                : plainEnumLabel(obligation.category)}
            </div>
          )}
          <h3 className="mt-1 font-black">
            {requirementLabel(obligation.type)}
          </h3>
          <div className="mt-2 text-xs font-bold uppercase tracking-wide text-slate-500">
            Required action
          </div>
          <p className="mt-1 text-lg font-black">
            {requiredActionLabel(obligation.type)}
          </p>
          {obligation.trigger && (
            <div className="mt-2 flex flex-wrap items-center gap-1 text-sm text-slate-600">
              <span>
                Generated by {plainEnumLabel(obligation.trigger.type)} completed
              </span>
              <ComplianceDate value={obligation.trigger.date} compact />
              <span>→ this obligation</span>
            </div>
          )}
        </div>
        <div>
          <ComplianceDate
            value={obligation.latest}
            label="Deadline"
            deadline
            operational
            empty={
              obligation.priority === "EMERGENCY"
                ? "Schedule immediately / follow MPP"
                : "No fixed legal latest date"
            }
          />
        </div>
        <div className="lg:justify-self-end">
          <StatusBadge color={urgency.color} label={urgency.label} />
        </div>
      </div>
      <details className="mt-3 text-sm">
        <summary className="cursor-pointer font-black text-emerald-800">
          Required action, triggering event, and rule details
        </summary>
        <div className="mt-3 grid gap-4 rounded-xl bg-slate-50 p-4 lg:grid-cols-2">
          <ComplianceWindow
            start={obligation.earliest}
            end={obligation.latest}
            label="Earliest and last valid completion dates"
          />
          {(obligation.targetStart || obligation.targetEnd) && (
            <ComplianceWindow
              start={obligation.targetStart}
              end={obligation.targetEnd}
              label="Recommended service dates"
            />
          )}
          {obligation.trigger && (
            <div className="lg:col-span-2">
              <div className="label">Generated from</div>
              <div className="mt-1 font-bold">
                {plainEnumLabel(obligation.trigger.type)} ·{" "}
                <ComplianceDate value={obligation.trigger.date} compact />
              </div>
              <div className="mt-1 text-xs text-slate-500">
                Audit event {obligation.trigger.id}
              </div>
            </div>
          )}
          <div className="lg:col-span-2">
            <Why>{obligation.reason}</Why>
          </div>
          <div className="rounded-lg bg-amber-50 p-3 text-amber-950 lg:col-span-2">
            <div className="label">If this is missed</div>
            <p className="mt-1 font-bold">
              {missedObligationConsequence({
                category: obligation.category,
                type: obligation.type,
                priority: obligation.priority,
              })}
            </p>
          </div>
          {obligation.sourceCitation && (
            <p className="text-xs font-bold text-slate-500 lg:col-span-2">
              Source: {obligation.sourceCitation}
            </p>
          )}
          {obligation.ruleSetVersion && (
            <p className="text-xs font-bold text-slate-500 lg:col-span-2">
              Generated by rule version: {obligation.ruleSetVersion}
            </p>
          )}
        </div>
      </details>
    </article>
  );
}
