export const SERVICE_EVENT_TYPES = [
  "ROUTINE_LEGIONELLA_SAMPLE_COLLECTED",
  "LEGIONELLA_RESULT_RECEIVED",
  "QUARTERLY_INSPECTION_COMPLETED",
  "STARTUP",
  "SHUTDOWN",
  "STARTUP_CLEANING_DISINFECTION",
  "SUMMERTIME_HYPERHALOGENATION",
  "HIGH_LEGIONELLA_DISINFECTION",
  "FULL_REMEDIATION",
  "POWER_FAILURE",
  "BIOCIDE_LOSS",
  "CONDUCTIVITY_CONTROL_FAILURE",
  "DOH_DIRECTED_SAMPLE",
  "OTHER_DOH_CONDITION",
  "MANUAL_RISK_EVENT",
  "WEEKLY_BIOLOGICAL_INDICATOR_RESULT",
  "CLEANING_COMPLETED",
  "REPORT_SUBMITTED",
] as const;

export type ServiceEventTypeValue = (typeof SERVICE_EVENT_TYPES)[number];
